### ISSUE TITLE
Upgraded packages

### ISSUE THREAD

**Issue by jagdishadusumalli** [andreychernih/railsbox#41]
How can we install the latest packages as below
Currently installs -> Upgrade to
postgres is 9.3 ->   9.5
nodejs 0.10.25 ->    5.50 && npm 3.5.3
nginx 1.4.6       ->   1.8.0

**Comment by andreychernih** [comment]
Currently, packages are installed using default Ubuntu repository (apt-get). Some of the packages are out of date because it's Ubuntu policy - they need to keep the system stable. If you feel like you need to install recent versions, you can customize your playbook to do it - just google how to install a recent version of the software in Ubuntu.
