### ISSUE TITLE
Why use VirtualBox in Docker (Experimental) implementation?

### ISSUE THREAD

**Issue by patakijv** [andreychernih/railsbox#57]
Great effort with this railsbox generator. Impressive.

I am curious why in the experimental docker effort you are also still using virtualbox in the mix?
The use of docker containers should replace the need for a virtual machine, right? I see that in your main vagrantfile as you configure the containers, for each container you call another vagrantfile which sets up a virtual machine itself as it does in your standard implementation. Can you explain this?

**Comment by andreychernih** [comment]
Yeah, I agree with what you're saying, @patakijv. Usually, a set of Dockerfiles and one `docker-compose.yml` to rule them all is sufficient. I don't even see why ansible should be used for such setup considering that all provisioning and configuration can be done inside Dockerfile using  standard DSL. I guess, at the time when I was doing initial railsbox development, I have not had enough Docker experience, that's why it ended up being a bit over-engineered. Of course, pull requests with a proper Docker usage are always welcome :)
